#!/bin/bash

function open_new_tab 
{
  gnome-terminal --window -e "bash -c \"source \"devel/setup.bash\"; $1; exec bash\""
  sleep 2
}

cd "$(dirname ${BASH_SOURCE[0]})";
source "/opt/ros/jade/setup.bash";

if [ "$#" -eq  "1" ]; then
  if [ $1 = "-C" ]; then
    catkin_make
  fi
fi

open_new_tab "roscore"
open_new_tab "rosrun map map_node <<< \"src/map/src/conffile \""
open_new_tab "rosrun lights lights_node"
open_new_tab "rosrun crossings crossings_node"
open_new_tab "rosrun vizualization vizualization_node"


